#!/bin/bash
# generate-script.sh

OUTFILE=generated-py.py		# Name of the file to generate.

(
cat <<'EOF'
#!/usr/bin/python3

def generated_hello_world():
	print("Hello World im generated by bash ;)")

generated_hello_world()
EOF
) > $OUTFILE

# Quoting the 'limit string' prevents variable expansion within the body
# of the above 'here document'. This perimits outputting literal strings
# in the output file.

if [ -f $OUTFILE ]
then
	chmod 755 $OUTFILE
else
	echo "Problem in crating file: \"$OUTFILE\"".
fi

exit 0
